sudo: required

services:
  - docker

install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export ORIGIN=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo https://github.com/$TRAVIS_REPO_SLUG; else echo https://github.com/$TRAVIS_PULL_REQUEST_SLUG; fi)
  - echo "Testing hipSYCL, branch $BRANCH from $ORIGIN"
  - docker build --build-arg hipsycl_branch=$BRANCH --build-arg hipsycl_origin=$ORIGIN install/docker/CUDA
#  - docker build --build-arg hipsycl_branch=$BRANCH --build-arg hipsycl_origin=$ORIGIN install/docker/ROCm
  
script:
  - docker images
